const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

const events = [
  { number: 1, month: "Jan", date: "01 Jan 2026", endDate: null, title: "New Year's Day", opportunityType: "Holiday Greeting", priority: "MEDIUM", postConcept: "Mrs Veds holiday greeting post in a styled look from AG", visualDirection: "Festive, celebratory aesthetic", captionDirection: "Warm, celebratory greeting", platforms: "Instagram Feed + Story", creativeBriefDue: "01 Dec 2025", creativeDue: "22 Dec 2025", status: "Not Started", notes: null },
  { number: 2, month: "Jan", date: "19 Jan 2026", endDate: "23 Jan 2026", title: "World Economic Forum (Davos)", opportunityType: "Thought Leadership", priority: "CRITICAL", postConcept: "LinkedIn article: Mrs Veds on retail resilience and the future of MENA commerce", visualDirection: "Professional backdrop or branded graphic. WEF/Forbes visual context.", captionDirection: "At Davos, one theme stands clear: the future of retail belongs to purpose-driven leaders", platforms: "LinkedIn + Twitter/X", creativeBriefDue: "19 Dec 2025", creativeDue: "09 Jan 2026", status: "Planned", notes: null },
  { number: 3, month: "Jan", date: "31 Jan 2026", endDate: null, title: "Dubai Fashion Week (SS26)", opportunityType: "DFW Coverage / GRWM", priority: "HIGH", postConcept: "Mrs Veds attends/covers Dubai Fashion Week — GRWM, front row moments, trend reports", visualDirection: "Fashion-forward, editorial. Street style aesthetic. Venue BTS.", captionDirection: "DFW 2026 — the looks, the moments, the brands — fashion authority tone", platforms: "Instagram Reel + Stories + TikTok", creativeBriefDue: "31 Dec 2025", creativeDue: "21 Jan 2026", status: "Not Started", notes: null },
  { number: 4, month: "Feb", date: "03 Feb 2026", endDate: "04 Feb 2026", title: "RLC Global Forum (Riyadh)", opportunityType: "Thought Leadership / Speaking", priority: "CRITICAL", postConcept: "Speaking moment or post-event recap reel at the RLC Global Forum podium.", visualDirection: "Stage photography, branded event backdrop, candid leadership shots.", captionDirection: "Honoured to join top retail leaders at RLCGlobalForum discussing the future of commerce", platforms: "LinkedIn + Instagram Reel + Story", creativeBriefDue: "03 Jan 2026", creativeDue: "24 Jan 2026", status: "Planned", notes: null },
  { number: 5, month: "Feb", date: "11 Feb 2026", endDate: null, title: "New York Fashion Week", opportunityType: "Trend Commentary", priority: "HIGH", postConcept: "Reel or Carousel: Mrs Veds NYFW trend picks — what to watch for AW26/27", visualDirection: "Mood board aesthetic: fashion week energy, editorial palette.", captionDirection: "NYFW kicks off fashion month — here are the trends I am tracking for the region", platforms: "Instagram Reel + Feed + Story", creativeBriefDue: "11 Jan 2026", creativeDue: "01 Feb 2026", status: "Planned", notes: null },
  { number: 6, month: "Feb", date: "14 Feb 2026", endDate: null, title: "Valentine's Day", opportunityType: "Gifting Guide / OOTD", priority: "HIGH", postConcept: "Mrs Veds shares her top Valentine's picks from across Apparel Group brands — OOTD look styled for the occasion", visualDirection: "Warm tones, roses/pinks. Close-up of styled outfit + gift flatlay.", captionDirection: "This Valentine's, I'm choosing [brand] for... — personal story-driven, link in bio to shop", platforms: "Instagram Reel + Feed + Story", creativeBriefDue: "14 Jan 2026", creativeDue: "04 Feb 2026", status: "Not Started", notes: null },
  { number: 7, month: "Feb", date: "18 Feb 2026", endDate: null, title: "Ramadan Begins", opportunityType: "Ramadan Series (Multi-Week)", priority: "CRITICAL", postConcept: "Mrs Veds Ramadan series — Iftar looks, suhoor moments, gifting guides, night market styling across AG", visualDirection: "Warm amber, gold tones. Night market aesthetic. Lifestyle + fashion.", captionDirection: "Ramadan Kareem — the looks, the mood, the gifting... — series across 4 weeks", platforms: "Instagram Reel Series + Story + TikTok", creativeBriefDue: "18 Jan 2026", creativeDue: "08 Feb 2026", status: "Not Started", notes: null },
  { number: 8, month: "Feb", date: "19 Feb 2026", endDate: null, title: "London Fashion Week", opportunityType: "Trend Commentary / OOTD", priority: "HIGH", postConcept: "Style reaction post or LFW trend review — avant-garde picks and RTW highlight reel.", visualDirection: "Editorial tones: grey/black/white fashion week aesthetic.", captionDirection: "London Fashion Week never disappoints. My top picks from LFW AW26/27", platforms: "Instagram Feed + Reel + Story", creativeBriefDue: "19 Jan 2026", creativeDue: "09 Feb 2026", status: "Planned", notes: null },
  { number: 9, month: "Feb", date: "25 Feb 2026", endDate: null, title: "Kuwait National Day", opportunityType: "Cultural / Brand Acknowledgement", priority: "MEDIUM", postConcept: "National pride post celebrating Kuwait — flag visuals, cultural nod.", visualDirection: "Kuwait flag palette, skyline or cultural motif.", captionDirection: "Celebrating Kuwait's journey and spirit on this National Day", platforms: "Instagram + Story + LinkedIn", creativeBriefDue: "25 Jan 2026", creativeDue: "15 Feb 2026", status: "Not Started", notes: null },
  { number: 10, month: "Feb", date: "26 Feb 2026", endDate: null, title: "Kuwait Liberation Day", opportunityType: "Cultural / Brand Acknowledgement", priority: "MEDIUM", postConcept: "Liberation Day tribute — resilience and pride.", visualDirection: "Kuwait flag palette, heritage imagery.", captionDirection: "Honouring Kuwait's resilience and freedom — Liberation Day", platforms: "Instagram + Story + LinkedIn", creativeBriefDue: "26 Jan 2026", creativeDue: "16 Feb 2026", status: "Not Started", notes: null },
  { number: 11, month: "Mar", date: "02 Mar 2026", endDate: "10 Mar 2026", title: "Milan Fashion Week", opportunityType: "Trend Commentary / OOTD", priority: "HIGH", postConcept: "Milan MFW highlights reel — luxury heritage brands, craftsmanship, leather goods focus.", visualDirection: "Rich, warm tones. Duomo backdrop or luxury editorial styling reference.", captionDirection: "Milan speaks in quality and heritage. My MFW edit for this season", platforms: "Instagram Reel + Feed + LinkedIn", creativeBriefDue: "02 Feb 2026", creativeDue: "20 Feb 2026", status: "Planned", notes: null },
  { number: 12, month: "Mar", date: "08 Mar 2026", endDate: null, title: "International Women's Day", opportunityType: "Women Empowerment Feature", priority: "HIGH", postConcept: "Mrs Veds shares her personal empowerment story + spotlights women at AG — authentic, inspiring", visualDirection: "Bold, empowering. Strong portrait. Candid behind-the-scenes.", captionDirection: "To the women who showed me what strength looks like... — personal, inspiring", platforms: "Instagram Feed + Reel + LinkedIn", creativeBriefDue: "08 Feb 2026", creativeDue: "26 Feb 2026", status: "Not Started", notes: null },
  { number: 13, month: "Mar", date: "20 Mar 2026", endDate: null, title: "Eid Al Fitr", opportunityType: "Eid OOTD Collection Drop", priority: "CRITICAL", postConcept: "Mrs Veds Eid collection — multiple Eid looks across AG brands, family/celebration context", visualDirection: "Festive, joyful, bright. Gold and jewel tones. Family/group setting ideal.", captionDirection: "Eid Mubarak — here's how I'm celebrating in [brand] — joyful, fashion-forward", platforms: "Instagram Reel + Feed + Story", creativeBriefDue: "20 Feb 2026", creativeDue: "10 Mar 2026", status: "Not Started", notes: null },
  { number: 14, month: "Mar", date: "21 Mar 2026", endDate: null, title: "Mother's Day (UAE)", opportunityType: "Tribute / Gift Guide", priority: "HIGH", postConcept: "Mrs Veds shares a personal tribute to motherhood + curated gifting edit from AG brands", visualDirection: "Soft, emotional. Lifestyle imagery. Video message format ideal.", captionDirection: "Heartfelt caption — personal story. CTA: Tag the mum in your life", platforms: "Instagram Reel + Story", creativeBriefDue: "21 Feb 2026", creativeDue: "11 Mar 2026", status: "Not Started", notes: null },
  { number: 15, month: "Apr", date: "07 Apr 2026", endDate: null, title: "World Health Day", opportunityType: "Awareness Moment", priority: "MEDIUM", postConcept: "Mrs Veds marks the awareness day with a personal, authentic post", visualDirection: "Clean, purposeful aesthetic", captionDirection: "Personal, empathetic caption tied to the awareness theme", platforms: "Instagram Feed + Story", creativeBriefDue: "07 Mar 2026", creativeDue: "28 Mar 2026", status: "Not Started", notes: null },
  { number: 16, month: "Apr", date: "08 Apr 2026", endDate: "10 Apr 2026", title: "Paris Fashion Week", opportunityType: "Trend Commentary / OOTD", priority: "CRITICAL", postConcept: "PFW couture moment — Mrs Veds top picks, OOTD, and brand commentary. Biggest fashion post of the year.", visualDirection: "Parisian aesthetic: Eiffel Tower, haute couture styling, editorial palette.", captionDirection: "Paris Fashion Week — the pinnacle. Here is everything I loved from PFW.", platforms: "Instagram Reel + Feed + Story + LinkedIn", creativeBriefDue: "08 Mar 2026", creativeDue: "29 Mar 2026", status: "Planned", notes: null },
  { number: 17, month: "Apr", date: "14 Apr 2026", endDate: "18 Apr 2026", title: "Arab Women Week & Summit (London)", opportunityType: "Women Empowerment / Speaking", priority: "CRITICAL", postConcept: "Lancaster House speaking engagement — Mrs Veds on Arab women in global leadership.", visualDirection: "Prestigious venue photography. Lancaster House interior, polished executive styling.", captionDirection: "At Arab Women Week Summit in London — honoured to share the stage with global trailblazers.", platforms: "LinkedIn + Instagram Feed + Reel", creativeBriefDue: "14 Mar 2026", creativeDue: "04 Apr 2026", status: "Planned", notes: null },
  { number: 18, month: "Apr", date: "17 Apr 2026", endDate: "19 Apr 2026", title: "F1 Saudi Arabian GP", opportunityType: "Lifestyle / Brand Activation", priority: "HIGH", postConcept: "Jeddah F1 — corporate hospitality + luxury automotive synergy. Mrs Veds OOTD and brand tie-in.", visualDirection: "Bold Saudi national spirit meets luxury fashion. Jeddah corniche backdrop.", captionDirection: "Jeddah Formula One. Where speed meets style in the Kingdom.", platforms: "Instagram Feed + Story + Reel", creativeBriefDue: "17 Mar 2026", creativeDue: "07 Apr 2026", status: "Planned", notes: null },
  { number: 19, month: "Apr", date: "22 Apr 2026", endDate: null, title: "Earth Day", opportunityType: "Awareness Moment", priority: "MEDIUM", postConcept: "Mrs Veds marks the awareness day with a personal, authentic post", visualDirection: "Clean, purposeful aesthetic", captionDirection: "Personal, empathetic caption tied to the awareness theme", platforms: "Instagram Feed + Story", creativeBriefDue: "22 Mar 2026", creativeDue: "12 Apr 2026", status: "Not Started", notes: null },
  { number: 20, month: "May", date: "26 May 2026", endDate: null, title: "Arafat Day & Eid Al Adha", opportunityType: "Eid Al Adha Styling", priority: "HIGH", postConcept: "Mrs Veds Eid Al Adha looks + gifting edit from AG brands", visualDirection: "Rich, warm, traditional-inspired tones. Celebratory styling.", captionDirection: "Eid Al Adha Mubarak — my Eid edit is here — warm, festive", platforms: "Instagram Reel + Feed + Story", creativeBriefDue: "26 Apr 2026", creativeDue: "16 May 2026", status: "Not Started", notes: null },
  { number: 21, month: "Jun", date: "30 Jun 2026", endDate: null, title: "World Social Media Day", opportunityType: "Behind-the-Scenes Creator Moment", priority: "MEDIUM", postConcept: "Mrs Veds shares a BTS moment of her content creation process + celebrates the community", visualDirection: "Candid, authentic. Creator desk/studio aesthetic. Light, fun.", captionDirection: "To every creator out there — thank you for inspiring me every day", platforms: "Instagram Reel + Story", creativeBriefDue: "30 May 2026", creativeDue: "20 Jun 2026", status: "Not Started", notes: null },
  { number: 22, month: "Jul", date: "30 Jul 2026", endDate: null, title: "International Friendship Day", opportunityType: "Friends & Fashion Collab", priority: "MEDIUM", postConcept: "Mrs Veds + friend(s) styling moment — group OOTD from AG brands", visualDirection: "Joyful, fun, group aesthetic. Bright and colourful.", captionDirection: "The best accessory? Your best friend — styled by [brand]", platforms: "Instagram Reel + Feed + Story", creativeBriefDue: "30 Jun 2026", creativeDue: "20 Jul 2026", status: "Not Started", notes: null },
  { number: 23, month: "Aug", date: "12 Aug 2026", endDate: null, title: "International Youth Day", opportunityType: "Awareness Moment", priority: "MEDIUM", postConcept: "Mrs Veds marks the awareness day with a personal, authentic post", visualDirection: "Clean, purposeful aesthetic", captionDirection: "Personal, empathetic caption tied to the awareness theme", platforms: "Instagram Feed + Story", creativeBriefDue: "12 Jul 2026", creativeDue: "02 Aug 2026", status: "Not Started", notes: null },
  { number: 24, month: "Aug", date: "21 Aug 2026", endDate: null, title: "World Entrepreneurs Day", opportunityType: "Entrepreneur Story", priority: "MEDIUM", postConcept: "Mrs Veds shares her entrepreneurship/creator journey — personal brand building", visualDirection: "Confident, aspirational. Power pose or workspace aesthetic.", captionDirection: "Building something you're proud of is the ultimate flex", platforms: "Instagram Feed + Reel", creativeBriefDue: "21 Jul 2026", creativeDue: "11 Aug 2026", status: "Not Started", notes: null },
  { number: 25, month: "Aug", date: "25 Aug 2026", endDate: null, title: "Back to School", opportunityType: "Back to School OOTD / Styling Guide", priority: "HIGH", postConcept: "Mrs Veds styles back-to-school looks from AG brands — relatable, aspirational", visualDirection: "Clean, fresh, school/campus aesthetic. Multiple outfit options.", captionDirection: "Back to school era — styled by [brand] — aspirational + relatable", platforms: "Instagram Reel + Carousel + Story", creativeBriefDue: "25 Jul 2026", creativeDue: "15 Aug 2026", status: "Not Started", notes: null },
  { number: 26, month: "Aug", date: "28 Aug 2026", endDate: null, title: "Emirati Women's Day", opportunityType: "Emirati Heritage Styling", priority: "HIGH", postConcept: "Mrs Veds celebrates Emirati Women's Day — styled in traditional-inspired looks from AG brands", visualDirection: "Rich, proud aesthetics. Traditional colour palette. Portrait/editorial.", captionDirection: "Proud to celebrate the strength of Emirati women — pride + identity", platforms: "Instagram Feed + Story + Reel", creativeBriefDue: "28 Jul 2026", creativeDue: "18 Aug 2026", status: "Not Started", notes: null },
  { number: 27, month: "Sep", date: "01 Sep 2026", endDate: "06 Sep 2026", title: "Dubai Fashion Week (SS27)", opportunityType: "Fashion / Brand Moment", priority: "CRITICAL", postConcept: "DFW SS27 — Mrs Veds front row, backstage access, OOTD series, brand showcase content.", visualDirection: "Dubai d3 aesthetic. Front-row fashion photography, designer encounters, editorial styling.", captionDirection: "Dubai Fashion Week SS27 — the region's most electric fashion moment is BACK.", platforms: "Instagram Reel + Feed + Story + LinkedIn", creativeBriefDue: "01 Aug 2026", creativeDue: "22 Aug 2026", status: "Planned", notes: null },
  { number: 28, month: "Sep", date: "23 Sep 2026", endDate: null, title: "Saudi National Day", opportunityType: "Saudi National Day Feature", priority: "MEDIUM", postConcept: "Mrs Veds Saudi National Day content — Saudi pride, AG regional celebration", visualDirection: "Green and white tones. Saudi cultural references.", captionDirection: "Happy Saudi National Day — celebrating with [brand] — regional pride", platforms: "Instagram Feed + Story", creativeBriefDue: "23 Aug 2026", creativeDue: "13 Sep 2026", status: "Not Started", notes: null },
  { number: 29, month: "Oct", date: "01 Oct 2026", endDate: null, title: "Pinktober (Breast Cancer)", opportunityType: "Pinktober Month-Long Series", priority: "HIGH", postConcept: "Mrs Veds wears pink across AG brands all October — awareness, support, survivor stories", visualDirection: "Pink across all content. Soft, supportive aesthetic. No heavy product push.", captionDirection: "Pink October — wearing it with purpose — awareness, community, not commercial", platforms: "Instagram Weekly Posts + Story", creativeBriefDue: "01 Sep 2026", creativeDue: "21 Sep 2026", status: "Not Started", notes: null },
  { number: 30, month: "Oct", date: "05 Oct 2026", endDate: "06 Oct 2026", title: "Retail Congress MENA", opportunityType: "Thought Leadership / Speaking", priority: "HIGH", postConcept: "Retail Congress panel or keynote recap — Mrs Veds on the future of MENA retail strategy.", visualDirection: "Conference photography. Dubai skyline backdrop, professional styling.", captionDirection: "At RetailCongressMENA — the conversations shaping the future of retail in our region.", platforms: "LinkedIn + Instagram Story", creativeBriefDue: "05 Sep 2026", creativeDue: "25 Sep 2026", status: "Planned", notes: null },
  { number: 31, month: "Oct", date: "06 Oct 2026", endDate: "08 Oct 2026", title: "ME Women Leaders Summit & Awards (KSA)", opportunityType: "Women Empowerment / Award", priority: "CRITICAL", postConcept: "Summit attendance + award recognition opportunity. Mrs Veds speech or acceptance moment.", visualDirection: "Award gala photography. Elegant KSA venue setting, red carpet or stage moment.", captionDirection: "The 6% barrier in executive leadership must be broken. Proud to be part of the solution.", platforms: "LinkedIn + Instagram Feed + Reel", creativeBriefDue: "06 Sep 2026", creativeDue: "26 Sep 2026", status: "Planned", notes: null },
  { number: 32, month: "Oct", date: "31 Oct 2026", endDate: null, title: "Halloween", opportunityType: "Costume / Fashion Moment", priority: "HIGH", postConcept: "Mrs Veds in a creative Halloween look styled from AG brands — fun, on-trend", visualDirection: "Dark/moody aesthetic. Dramatic look. BTS + final reveal format.", captionDirection: "Playful, fun tone. Reveal format. Dressed by [brand]", platforms: "Instagram Reel + TikTok + Story", creativeBriefDue: "30 Sep 2026", creativeDue: "21 Oct 2026", status: "Not Started", notes: null },
  { number: 33, month: "Oct", date: "31 Oct 2026", endDate: null, title: "Dubai Fitness Challenge (30x30)", opportunityType: "DFC Fitness Style Series", priority: "HIGH", postConcept: "Mrs Veds 30x30 challenge journey — activewear styling from AG brands, 30 days of content", visualDirection: "Active, energetic, outdoor. Workout aesthetic, bright and healthy.", captionDirection: "30 days, 30 mins — joining the DFC in [brand activewear] — challenge energy", platforms: "Instagram Reel Series + Story + TikTok", creativeBriefDue: "30 Sep 2026", creativeDue: "21 Oct 2026", status: "Not Started", notes: null },
  { number: 34, month: "Nov", date: "02 Nov 2026", endDate: null, title: "Diwali", opportunityType: "Diwali Fashion & Gifting", priority: "HIGH", postConcept: "Mrs Veds Diwali styling — festive, colourful looks + gifting from AG brands", visualDirection: "Jewel tones, candles, festive diyas. Rich and celebratory.", captionDirection: "Diwali with [brand] — the looks that light up the room — warm, inclusive", platforms: "Instagram Feed + Reel + Story", creativeBriefDue: "02 Oct 2026", creativeDue: "23 Oct 2026", status: "Not Started", notes: null },
  { number: 35, month: "Nov", date: "03 Nov 2026", endDate: null, title: "UAE Flag Day", opportunityType: "Awareness Moment", priority: "MEDIUM", postConcept: "Mrs Veds marks the awareness day with a personal, authentic post", visualDirection: "Clean, purposeful aesthetic", captionDirection: "Personal, empathetic caption tied to the awareness theme", platforms: "Instagram Feed + Story", creativeBriefDue: "03 Oct 2026", creativeDue: "24 Oct 2026", status: "Not Started", notes: null },
  { number: 36, month: "Nov", date: "18 Nov 2026", endDate: null, title: "Oman National Day", opportunityType: "Cultural / Brand Acknowledgement", priority: "MEDIUM", postConcept: "National Day tribute to Oman — heritage and modernity.", visualDirection: "Oman flag palette, scenic Muscat or cultural landmarks.", captionDirection: "Celebrating the beauty and heritage of Oman on National Day", platforms: "Instagram + Story + LinkedIn", creativeBriefDue: "18 Oct 2026", creativeDue: "08 Nov 2026", status: "Not Started", notes: null },
  { number: 37, month: "Dec", date: "02 Dec 2026", endDate: null, title: "UAE National Day", opportunityType: "UAE Pride / National Day OOTD", priority: "HIGH", postConcept: "Mrs Veds National Day look — UAE flag colours, patriotic styling from AG brands", visualDirection: "Red, white, green, black. UAE flag backdrop. Pride and celebration.", captionDirection: "Happy National Day — 55 years of dreams — proud, celebratory", platforms: "Instagram Feed + Story + Reel", creativeBriefDue: "02 Nov 2026", creativeDue: "22 Nov 2026", status: "Not Started", notes: null },
  { number: 38, month: "Dec", date: "04 Dec 2026", endDate: "06 Dec 2026", title: "F1 Abu Dhabi Grand Prix", opportunityType: "Lifestyle / Hospitality", priority: "CRITICAL", postConcept: "Season finale on Yas Island — Mrs Veds OOTD + corporate hospitality + brand activation.", visualDirection: "Yas Island luxury aesthetic. Sunset over the circuit, glamour hospitality suite.", captionDirection: "The final lap of the F1 season — and Abu Dhabi saves the BEST for last.", platforms: "Instagram Reel + Feed + Story + LinkedIn", creativeBriefDue: "04 Nov 2026", creativeDue: "24 Nov 2026", status: "Planned", notes: null },
  { number: 39, month: "Dec", date: "14 Dec 2026", endDate: "15 Dec 2026", title: "Forbes ME Women's Summit (Riyadh)", opportunityType: "Women Empowerment / Speaking", priority: "CRITICAL", postConcept: "Forbes ME Women Summit 4th edition — Mrs Veds as speaker or honoree. Theme: Limitless Inspiration.", visualDirection: "Forbes summit stage photography. Elegant Riyadh venue, award-night styling.", captionDirection: "Limitless Inspiration — that is the theme at ForbesMEWomen2026 and it could not be more fitting.", platforms: "LinkedIn + Instagram Reel + Feed", creativeBriefDue: "14 Nov 2026", creativeDue: "04 Dec 2026", status: "Planned", notes: null },
  { number: 40, month: "Dec", date: "16 Dec 2026", endDate: null, title: "Bahrain National Day", opportunityType: "Cultural / Brand Acknowledgement", priority: "MEDIUM", postConcept: "National Day tribute to Bahrain — pearl of the Gulf.", visualDirection: "Bahrain flag palette, Manama skyline or cultural motifs.", captionDirection: "Happy National Day to the Kingdom of Bahrain", platforms: "Instagram + Story + LinkedIn", creativeBriefDue: "16 Nov 2026", creativeDue: "06 Dec 2026", status: "Not Started", notes: null },
  { number: 41, month: "Dec", date: "18 Dec 2026", endDate: null, title: "Qatar National Day", opportunityType: "Cultural / Brand Acknowledgement", priority: "MEDIUM", postConcept: "Qatar National Day greeting post — Mrs Veds acknowledging Apparel Group presence in Qatar.", visualDirection: "Qatar maroon and white palette. National pride visual.", captionDirection: "Wishing our friends and partners in Qatar a proud and joyful National Day.", platforms: "Instagram Story + LinkedIn", creativeBriefDue: "18 Nov 2026", creativeDue: "08 Dec 2026", status: "Planned", notes: null },
  { number: 42, month: "Dec", date: "25 Dec 2026", endDate: null, title: "Christmas Day", opportunityType: "Gifting Haul / Christmas OOTD", priority: "HIGH", postConcept: "Mrs Veds Christmas gifting haul + festive OOTD across AG brands", visualDirection: "Festive, warm, cosy. Home setting with gifting. Unboxing style.", captionDirection: "My Christmas picks from @[brand] — authentic, warm tone", platforms: "Instagram Reel + Feed + Story", creativeBriefDue: "25 Nov 2026", creativeDue: "15 Dec 2026", status: "Not Started", notes: null },
]

async function main() {
  const hashedPassword = await bcrypt.hash('admin123', 10)

  // Admin user
  await prisma.user.upsert({
    where: { email: 'sims@admin.app' },
    update: {},
    create: {
      name: 'Karim',
      email: 'sims@admin.app',
      password: hashedPassword,
      role: 'ADMIN',
    },
  })

  // Approver 1
  await prisma.user.upsert({
    where: { email: 'editor@sims.app' },
    update: {},
    create: {
      name: 'Anda',
      email: 'editor@sims.app',
      password: await bcrypt.hash('admin123', 10),
      role: 'APPROVER',
    },
  })

  // Approver 2
  await prisma.user.upsert({
    where: { email: 'admin@sims.app' },
    update: {},
    create: {
      name: 'Mrs Veds',
      email: 'admin@sims.app',
      password: await bcrypt.hash('admin123', 10),
      role: 'APPROVER',
    },
  })

  for (const event of events) {
    await prisma.event.create({ data: event })
  }

  console.log('Seeded 42 events + 3 users')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
