const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

const events = [
  { number: 1, month: 'Jan', date: '01 Jan 2026', endDate: null, title: 'New Year\'s Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '17 Nov 2025', round1Due: '02 Dec 2025', round2Due: '07 Dec 2025', finalCreativeDue: '12 Dec 2025', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 2, month: 'Jan', date: '31 Jan 2026', endDate: null, title: 'Dubai Fashion Week', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '17 Dec 2025', round1Due: '01 Jan 2026', round2Due: '06 Jan 2026', finalCreativeDue: '11 Jan 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 3, month: 'Jan', date: '19 Jan 2026', endDate: '23 Jan 2026', title: 'DAVOS (19-23 Jan)', category: 'Sponsorships', opportunityType: 'Sponsorships', priority: 'CRITICAL', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '20 Nov 2025', round1Due: '05 Dec 2025', round2Due: '10 Dec 2025', finalCreativeDue: '15 Dec 2025', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 4, month: 'Feb', date: '14 Feb 2026', endDate: null, title: 'Valentine\'s Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '31 Dec 2025', round1Due: '15 Jan 2026', round2Due: '20 Jan 2026', finalCreativeDue: '25 Jan 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 5, month: 'Feb', date: '18 Feb 2026', endDate: null, title: 'Ramadan', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '04 Jan 2026', round1Due: '19 Jan 2026', round2Due: '24 Jan 2026', finalCreativeDue: '29 Jan 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 6, month: 'Feb', date: '22 Feb 2026', endDate: null, title: 'Saudi Founding Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '08 Jan 2026', round1Due: '23 Jan 2026', round2Due: '28 Jan 2026', finalCreativeDue: '02 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 7, month: 'Feb', date: '25 Feb 2026', endDate: null, title: 'Kuwait National Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '11 Jan 2026', round1Due: '26 Jan 2026', round2Due: '31 Jan 2026', finalCreativeDue: '05 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 8, month: 'Feb', date: '14 Feb 2026', endDate: null, title: 'Valentine\'s Day Campaign', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '31 Dec 2025', round1Due: '15 Jan 2026', round2Due: '20 Jan 2026', finalCreativeDue: '25 Jan 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 9, month: 'Feb', date: '18 Feb 2026', endDate: '18 Mar 2026', title: 'Ramadan Campaign (18 Feb - 18 Mar)', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '04 Jan 2026', round1Due: '19 Jan 2026', round2Due: '24 Jan 2026', finalCreativeDue: '29 Jan 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 10, month: 'Feb', date: '18 Feb 2026', endDate: null, title: 'Ramadan Gifting', category: 'Gifting', opportunityType: 'Gifting', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '20 Dec 2025', round1Due: '04 Jan 2026', round2Due: '09 Jan 2026', finalCreativeDue: '14 Jan 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 11, month: 'Feb', date: '03 Feb 2026', endDate: '04 Feb 2026', title: 'KSA RLC (3-4 Feb)', category: 'Sponsorships', opportunityType: 'Sponsorships', priority: 'CRITICAL', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '05 Dec 2025', round1Due: '20 Dec 2025', round2Due: '25 Dec 2025', finalCreativeDue: '30 Dec 2025', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 12, month: 'Feb', date: '26 Feb 2026', endDate: null, title: 'Kora Suhoor Event', category: 'Corporate Event', opportunityType: 'Corporate Event', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '28 Dec 2025', round1Due: '12 Jan 2026', round2Due: '17 Jan 2026', finalCreativeDue: '22 Jan 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 13, month: 'Feb', date: '18 Feb 2026', endDate: '18 Mar 2026', title: 'CSR - Gift it Forward  (18 Feb - 18 Mar)', category: 'HR & CSR', opportunityType: 'HR & CSR', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '20 Dec 2025', round1Due: '04 Jan 2026', round2Due: '09 Jan 2026', finalCreativeDue: '14 Jan 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 14, month: 'Feb', date: '27 Feb 2026', endDate: null, title: 'Kris Fade Birthday', category: 'PR Birthdays', opportunityType: 'PR Birthdays', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '13 Jan 2026', round1Due: '28 Jan 2026', round2Due: '02 Feb 2026', finalCreativeDue: '07 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 15, month: 'Feb', date: '26 Feb 2026', endDate: null, title: 'Coca Cola Arena Basketball Events', category: 'Coca Cola Arena', opportunityType: 'Coca Cola Arena', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '12 Jan 2026', round1Due: '27 Jan 2026', round2Due: '01 Feb 2026', finalCreativeDue: '06 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 16, month: 'Mar', date: '08 Mar 2026', endDate: null, title: 'International Women\'s Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '22 Jan 2026', round1Due: '06 Feb 2026', round2Due: '11 Feb 2026', finalCreativeDue: '16 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 17, month: 'Mar', date: '11 Mar 2026', endDate: null, title: 'Saudi Flag Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '25 Jan 2026', round1Due: '09 Feb 2026', round2Due: '14 Feb 2026', finalCreativeDue: '19 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 18, month: 'Mar', date: '15 Mar 2026', endDate: null, title: 'Children\'s Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '29 Jan 2026', round1Due: '13 Feb 2026', round2Due: '18 Feb 2026', finalCreativeDue: '23 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 19, month: 'Mar', date: '20 Mar 2026', endDate: null, title: 'Eid Al-Fitr', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '03 Feb 2026', round1Due: '18 Feb 2026', round2Due: '23 Feb 2026', finalCreativeDue: '28 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 20, month: 'Mar', date: '21 Mar 2026', endDate: null, title: 'Mother\'s Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '04 Feb 2026', round1Due: '19 Feb 2026', round2Due: '24 Feb 2026', finalCreativeDue: '01 Mar 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 21, month: 'Mar', date: '08 Mar 2026', endDate: null, title: 'International Women\'s Day Campaign', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '22 Jan 2026', round1Due: '06 Feb 2026', round2Due: '11 Feb 2026', finalCreativeDue: '16 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 22, month: 'Mar', date: '20 Mar 2026', endDate: null, title: 'Eid Al-Fitr Campaign', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '03 Feb 2026', round1Due: '18 Feb 2026', round2Due: '23 Feb 2026', finalCreativeDue: '28 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 23, month: 'Mar', date: '21 Mar 2026', endDate: null, title: 'Mother\'s Day Campaign', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '04 Feb 2026', round1Due: '19 Feb 2026', round2Due: '24 Feb 2026', finalCreativeDue: '01 Mar 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 24, month: 'Mar', date: '20 Mar 2026', endDate: null, title: 'Eid Al-Fitr Gifting', category: 'Gifting', opportunityType: 'Gifting', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '19 Jan 2026', round1Due: '03 Feb 2026', round2Due: '08 Feb 2026', finalCreativeDue: '13 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 25, month: 'Mar', date: '21 Mar 2026', endDate: null, title: 'Mother\'s Day Gifting', category: 'Gifting', opportunityType: 'Gifting', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '20 Jan 2026', round1Due: '04 Feb 2026', round2Due: '09 Feb 2026', finalCreativeDue: '14 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 26, month: 'Mar', date: '26 Mar 2026', endDate: null, title: 'Country Strategy Meeting Turkey', category: 'Corporate Event', opportunityType: 'Corporate Event', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '25 Jan 2026', round1Due: '09 Feb 2026', round2Due: '14 Feb 2026', finalCreativeDue: '19 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 27, month: 'Mar', date: '13 Mar 2026', endDate: null, title: 'Rosemin Manji Birthday', category: 'PR Birthdays', opportunityType: 'PR Birthdays', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '27 Jan 2026', round1Due: '11 Feb 2026', round2Due: '16 Feb 2026', finalCreativeDue: '21 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 28, month: 'Mar', date: '18 Mar 2026', endDate: null, title: 'Shereen Mitwalli Birthday', category: 'PR Birthdays', opportunityType: 'PR Birthdays', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '01 Feb 2026', round1Due: '16 Feb 2026', round2Due: '21 Feb 2026', finalCreativeDue: '26 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 29, month: 'Mar', date: '12 Mar 2026', endDate: null, title: 'Coca Cola Arena Basketball Events (12, 15, 24 Mar)', category: 'Coca Cola Arena', opportunityType: 'Coca Cola Arena', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '26 Jan 2026', round1Due: '10 Feb 2026', round2Due: '15 Feb 2026', finalCreativeDue: '20 Feb 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 30, month: 'Apr', date: '22 Apr 2026', endDate: null, title: 'Earth Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '08 Mar 2026', round1Due: '23 Mar 2026', round2Due: '28 Mar 2026', finalCreativeDue: '02 Apr 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 31, month: 'Apr', date: '22 Apr 2026', endDate: '24 Apr 2026', title: 'World Economic Forum in Saudi Arabia (22-24 Apr)', category: 'Corporate Event', opportunityType: 'Corporate Event', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '21 Feb 2026', round1Due: '08 Mar 2026', round2Due: '13 Mar 2026', finalCreativeDue: '18 Mar 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 32, month: 'Apr', date: '03 Apr 2026', endDate: null, title: 'Coca Cola Arena Basketball Events (3, 5, 10, 13, 17 Apr)', category: 'Coca Cola Arena', opportunityType: 'Coca Cola Arena', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '17 Feb 2026', round1Due: '04 Mar 2026', round2Due: '09 Mar 2026', finalCreativeDue: '14 Mar 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 33, month: 'Apr', date: '19 Apr 2026', endDate: null, title: 'Coca Cola Arena Atif Aslan Concert', category: 'Coca Cola Arena', opportunityType: 'Coca Cola Arena', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '05 Mar 2026', round1Due: '20 Mar 2026', round2Due: '25 Mar 2026', finalCreativeDue: '30 Mar 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 34, month: 'May', date: '10 May 2026', endDate: null, title: 'International Mother\'s Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '26 Mar 2026', round1Due: '10 Apr 2026', round2Due: '15 Apr 2026', finalCreativeDue: '20 Apr 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 35, month: 'May', date: '26 May 2026', endDate: null, title: 'Arafat Day - Eid Al Adha', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '11 Apr 2026', round1Due: '26 Apr 2026', round2Due: '01 May 2026', finalCreativeDue: '06 May 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 36, month: 'May', date: '08 May 2026', endDate: null, title: 'Mona Kattan Birthday', category: 'PR Birthdays', opportunityType: 'PR Birthdays', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '24 Mar 2026', round1Due: '08 Apr 2026', round2Due: '13 Apr 2026', finalCreativeDue: '18 Apr 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 37, month: 'May', date: '10 May 2026', endDate: null, title: 'Coca Cola Arena TBC Concert', category: 'Coca Cola Arena', opportunityType: 'Coca Cola Arena', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '26 Mar 2026', round1Due: '10 Apr 2026', round2Due: '15 Apr 2026', finalCreativeDue: '20 Apr 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 38, month: 'Jun', date: '21 Jun 2026', endDate: null, title: 'Father\'s Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '07 May 2026', round1Due: '22 May 2026', round2Due: '27 May 2026', finalCreativeDue: '01 Jun 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 39, month: 'Jun', date: '30 Jun 2026', endDate: null, title: 'World Social Media Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '16 May 2026', round1Due: '31 May 2026', round2Due: '05 Jun 2026', finalCreativeDue: '10 Jun 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 40, month: 'Jun', date: '01 Jun 2026', endDate: null, title: 'AG 30 Years Campaign (JUN)', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '17 Apr 2026', round1Due: '02 May 2026', round2Due: '07 May 2026', finalCreativeDue: '12 May 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 41, month: 'Jun', date: '21 Jun 2026', endDate: null, title: 'Father\'s Day Campaign', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '07 May 2026', round1Due: '22 May 2026', round2Due: '27 May 2026', finalCreativeDue: '01 Jun 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 42, month: 'Jun', date: '01 Jun 2026', endDate: null, title: 'Summer Campaign (JUN)', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '17 Apr 2026', round1Due: '02 May 2026', round2Due: '07 May 2026', finalCreativeDue: '12 May 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 43, month: 'Jun', date: '01 Jun 2026', endDate: null, title: 'AG 30 Years Gifting (JUN)', category: 'Gifting', opportunityType: 'Gifting', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '02 Apr 2026', round1Due: '17 Apr 2026', round2Due: '22 Apr 2026', finalCreativeDue: '27 Apr 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 44, month: 'Jun', date: '21 Jun 2026', endDate: null, title: 'Father\'s Day Gifting', category: 'Gifting', opportunityType: 'Gifting', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '22 Apr 2026', round1Due: '07 May 2026', round2Due: '12 May 2026', finalCreativeDue: '17 May 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 45, month: 'Jun', date: '01 Jun 2026', endDate: null, title: 'Summer Campaign Gifting (JUN)', category: 'Gifting', opportunityType: 'Gifting', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '02 Apr 2026', round1Due: '17 Apr 2026', round2Due: '22 Apr 2026', finalCreativeDue: '27 Apr 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 46, month: 'Jun', date: '11 Jun 2026', endDate: '19 Jul 2026', title: 'FIFA World Cup (11 Jun - 19 Jul)', category: 'Corporate Event', opportunityType: 'Corporate Event', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '12 Apr 2026', round1Due: '27 Apr 2026', round2Due: '02 May 2026', finalCreativeDue: '07 May 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 47, month: 'Jun', date: '23 Jun 2026', endDate: '25 Jun 2026', title: 'Annual Meeting of the New Champions (China) (23-25 Jun)', category: 'Corporate Event', opportunityType: 'Corporate Event', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '24 Apr 2026', round1Due: '09 May 2026', round2Due: '14 May 2026', finalCreativeDue: '19 May 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 48, month: 'Jun', date: '11 Jun 2026', endDate: null, title: 'Coca Cola Arena TBC Concert - The Beach Boys', category: 'Coca Cola Arena', opportunityType: 'Coca Cola Arena', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '27 Apr 2026', round1Due: '12 May 2026', round2Due: '17 May 2026', finalCreativeDue: '22 May 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 49, month: 'Jul', date: '01 Jul 2026', endDate: null, title: 'Selina Ved Wedding (JUL)', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '17 May 2026', round1Due: '01 Jun 2026', round2Due: '06 Jun 2026', finalCreativeDue: '11 Jun 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 50, month: 'Jul', date: '30 Jul 2026', endDate: null, title: 'International Friendship Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '15 Jun 2026', round1Due: '30 Jun 2026', round2Due: '05 Jul 2026', finalCreativeDue: '10 Jul 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 51, month: 'Jul', date: '01 Jul 2026', endDate: null, title: 'Back to School Campaign (JUL - SEP)', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '17 May 2026', round1Due: '01 Jun 2026', round2Due: '06 Jun 2026', finalCreativeDue: '11 Jun 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 52, month: 'Jul', date: '01 Jul 2026', endDate: null, title: 'Back to School Gifting (JUL)', category: 'Gifting', opportunityType: 'Gifting', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '02 May 2026', round1Due: '17 May 2026', round2Due: '22 May 2026', finalCreativeDue: '27 May 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 53, month: 'Jul', date: '30 Jul 2026', endDate: null, title: 'Selina’s Wedding', category: 'Corporate Event', opportunityType: 'Corporate Event', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '31 May 2026', round1Due: '15 Jun 2026', round2Due: '20 Jun 2026', finalCreativeDue: '25 Jun 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 54, month: 'Aug', date: '12 Aug 2026', endDate: null, title: 'International Youth Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '28 Jun 2026', round1Due: '13 Jul 2026', round2Due: '18 Jul 2026', finalCreativeDue: '23 Jul 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 55, month: 'Aug', date: '21 Aug 2026', endDate: null, title: 'World Entrepreneurs Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '07 Jul 2026', round1Due: '22 Jul 2026', round2Due: '27 Jul 2026', finalCreativeDue: '01 Aug 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 56, month: 'Aug', date: '25 Aug 2026', endDate: null, title: 'Back to School', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '11 Jul 2026', round1Due: '26 Jul 2026', round2Due: '31 Jul 2026', finalCreativeDue: '05 Aug 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 57, month: 'Aug', date: '28 Aug 2026', endDate: null, title: 'Emirati Women\'s Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '14 Jul 2026', round1Due: '29 Jul 2026', round2Due: '03 Aug 2026', finalCreativeDue: '08 Aug 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 58, month: 'Aug', date: '28 Aug 2026', endDate: null, title: 'Emirati Women\'s Day Campaign', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '14 Jul 2026', round1Due: '29 Jul 2026', round2Due: '03 Aug 2026', finalCreativeDue: '08 Aug 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 59, month: 'Aug', date: '28 Aug 2026', endDate: null, title: 'Emirati Women\'s Day Gifting', category: 'Gifting', opportunityType: 'Gifting', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '29 Jun 2026', round1Due: '14 Jul 2026', round2Due: '19 Jul 2026', finalCreativeDue: '24 Jul 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 60, month: 'Aug', date: '06 Aug 2026', endDate: null, title: 'Safa Siddiqui Birthday', category: 'PR Birthdays', opportunityType: 'PR Birthdays', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '22 Jun 2026', round1Due: '07 Jul 2026', round2Due: '12 Jul 2026', finalCreativeDue: '17 Jul 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 61, month: 'Aug', date: '02 Aug 2026', endDate: null, title: 'Coca Cola Arena DEF Lepard Concert', category: 'Coca Cola Arena', opportunityType: 'Coca Cola Arena', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '18 Jun 2026', round1Due: '03 Jul 2026', round2Due: '08 Jul 2026', finalCreativeDue: '13 Jul 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 62, month: 'Sep', date: '23 Sep 2026', endDate: null, title: 'Saudi National Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '09 Aug 2026', round1Due: '24 Aug 2026', round2Due: '29 Aug 2026', finalCreativeDue: '03 Sep 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 63, month: 'Sep', date: '01 Sep 2026', endDate: null, title: 'Fall/Winter (SEP)', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '18 Jul 2026', round1Due: '02 Aug 2026', round2Due: '07 Aug 2026', finalCreativeDue: '12 Aug 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 64, month: 'Sep', date: '01 Sep 2026', endDate: null, title: 'Winter Campaign (SEP)', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '18 Jul 2026', round1Due: '02 Aug 2026', round2Due: '07 Aug 2026', finalCreativeDue: '12 Aug 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 65, month: 'Sep', date: '01 Sep 2026', endDate: null, title: 'Country Strategy Meeting on Egypt (SEP)', category: 'Corporate Event', opportunityType: 'Corporate Event', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '03 Jul 2026', round1Due: '18 Jul 2026', round2Due: '23 Jul 2026', finalCreativeDue: '28 Jul 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 66, month: 'Sep', date: '12 Sep 2026', endDate: null, title: 'Jessica Kahawaty Birthday', category: 'PR Birthdays', opportunityType: 'PR Birthdays', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '29 Jul 2026', round1Due: '13 Aug 2026', round2Due: '18 Aug 2026', finalCreativeDue: '23 Aug 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 67, month: 'Oct', date: '01 Oct 2026', endDate: null, title: 'Pinktober', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '17 Aug 2026', round1Due: '01 Sep 2026', round2Due: '06 Sep 2026', finalCreativeDue: '11 Sep 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 68, month: 'Oct', date: '10 Oct 2026', endDate: null, title: 'World Mental Health Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '26 Aug 2026', round1Due: '10 Sep 2026', round2Due: '15 Sep 2026', finalCreativeDue: '20 Sep 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 69, month: 'Oct', date: '17 Oct 2026', endDate: null, title: 'Omani Women’s Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '02 Sep 2026', round1Due: '17 Sep 2026', round2Due: '22 Sep 2026', finalCreativeDue: '27 Sep 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 70, month: 'Oct', date: '31 Oct 2026', endDate: null, title: 'Halloween', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '16 Sep 2026', round1Due: '01 Oct 2026', round2Due: '06 Oct 2026', finalCreativeDue: '11 Oct 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 71, month: 'Oct', date: '31 Oct 2026', endDate: '29 Nov 2026', title: 'Dubai Fitness Challenge Campaign (31 Oct - 29 Nov)', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '16 Sep 2026', round1Due: '01 Oct 2026', round2Due: '06 Oct 2026', finalCreativeDue: '11 Oct 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 72, month: 'Oct', date: '01 Oct 2026', endDate: null, title: 'CSR - Pinktober', category: 'HR & CSR', opportunityType: 'HR & CSR', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '02 Aug 2026', round1Due: '17 Aug 2026', round2Due: '22 Aug 2026', finalCreativeDue: '27 Aug 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 73, month: 'Oct', date: '01 Oct 2026', endDate: null, title: 'HR - Apparel Got Talent (OCT)', category: 'HR & CSR', opportunityType: 'HR & CSR', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '02 Aug 2026', round1Due: '17 Aug 2026', round2Due: '22 Aug 2026', finalCreativeDue: '27 Aug 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 74, month: 'Oct', date: '31 Oct 2026', endDate: null, title: 'HR - Dubai Fitness Challenge', category: 'HR & CSR', opportunityType: 'HR & CSR', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '01 Sep 2026', round1Due: '16 Sep 2026', round2Due: '21 Sep 2026', finalCreativeDue: '26 Sep 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 75, month: 'Oct', date: '02 Oct 2026', endDate: null, title: 'Huda Kattan Birthday', category: 'PR Birthdays', opportunityType: 'PR Birthdays', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '18 Aug 2026', round1Due: '02 Sep 2026', round2Due: '07 Sep 2026', finalCreativeDue: '12 Sep 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 76, month: 'Oct', date: '12 Oct 2026', endDate: null, title: 'Amira Sajwani Birthday', category: 'PR Birthdays', opportunityType: 'PR Birthdays', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '28 Aug 2026', round1Due: '12 Sep 2026', round2Due: '17 Sep 2026', finalCreativeDue: '22 Sep 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 77, month: 'Oct', date: '03 Oct 2026', endDate: null, title: 'Coca Cola Arena Richard Marx Concert', category: 'Coca Cola Arena', opportunityType: 'Coca Cola Arena', priority: 'LOW', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '19 Aug 2026', round1Due: '03 Sep 2026', round2Due: '08 Sep 2026', finalCreativeDue: '13 Sep 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 78, month: 'Nov', date: '01 Nov 2026', endDate: '30 Nov 2026', title: 'Movember (1-30 Nov)', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '17 Sep 2026', round1Due: '02 Oct 2026', round2Due: '07 Oct 2026', finalCreativeDue: '12 Oct 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 79, month: 'Nov', date: '02 Nov 2026', endDate: null, title: 'Diwali', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '18 Sep 2026', round1Due: '03 Oct 2026', round2Due: '08 Oct 2026', finalCreativeDue: '13 Oct 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 80, month: 'Nov', date: '03 Nov 2026', endDate: null, title: 'UAE Flag Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '19 Sep 2026', round1Due: '04 Oct 2026', round2Due: '09 Oct 2026', finalCreativeDue: '14 Oct 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 81, month: 'Nov', date: '11 Nov 2026', endDate: null, title: 'Single\'s Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '27 Sep 2026', round1Due: '12 Oct 2026', round2Due: '17 Oct 2026', finalCreativeDue: '22 Oct 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 82, month: 'Nov', date: '18 Nov 2026', endDate: null, title: 'Oman National Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '04 Oct 2026', round1Due: '19 Oct 2026', round2Due: '24 Oct 2026', finalCreativeDue: '29 Oct 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 83, month: 'Nov', date: '02 Nov 2026', endDate: null, title: 'Diwali Campaign', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '18 Sep 2026', round1Due: '03 Oct 2026', round2Due: '08 Oct 2026', finalCreativeDue: '13 Oct 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 84, month: 'Nov', date: '02 Nov 2026', endDate: null, title: 'Diwali Gifting', category: 'Gifting', opportunityType: 'Gifting', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '03 Sep 2026', round1Due: '18 Sep 2026', round2Due: '23 Sep 2026', finalCreativeDue: '28 Sep 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 85, month: 'Nov', date: '03 Nov 2026', endDate: null, title: 'UAE Flag Day', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '19 Sep 2026', round1Due: '04 Oct 2026', round2Due: '09 Oct 2026', finalCreativeDue: '14 Oct 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 86, month: 'Dec', date: '02 Dec 2026', endDate: null, title: 'UAE National Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '18 Oct 2026', round1Due: '02 Nov 2026', round2Due: '07 Nov 2026', finalCreativeDue: '12 Nov 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 87, month: 'Dec', date: '16 Dec 2026', endDate: null, title: 'Bahrain National Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '01 Nov 2026', round1Due: '16 Nov 2026', round2Due: '21 Nov 2026', finalCreativeDue: '26 Nov 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 88, month: 'Dec', date: '18 Dec 2026', endDate: null, title: 'Qatar National Day', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '03 Nov 2026', round1Due: '18 Nov 2026', round2Due: '23 Nov 2026', finalCreativeDue: '28 Nov 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 89, month: 'Dec', date: '25 Dec 2026', endDate: null, title: 'Christmas', category: 'Social/Key Moments', opportunityType: 'Social/Key Moments', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '10 Nov 2026', round1Due: '25 Nov 2026', round2Due: '30 Nov 2026', finalCreativeDue: '05 Dec 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 90, month: 'Dec', date: '02 Dec 2026', endDate: null, title: 'UAE National Day Campaign', category: 'Corporate Campaign', opportunityType: 'Corporate Campaign', priority: 'HIGH', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '18 Oct 2026', round1Due: '02 Nov 2026', round2Due: '07 Nov 2026', finalCreativeDue: '12 Nov 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 91, month: 'Dec', date: '25 Dec 2026', endDate: null, title: 'Festive Gifting', category: 'Gifting', opportunityType: 'Gifting', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '26 Oct 2026', round1Due: '10 Nov 2026', round2Due: '15 Nov 2026', finalCreativeDue: '20 Nov 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
  { number: 92, month: 'Dec', date: '01 Dec 2026', endDate: null, title: 'CSR - Donation Certificate (DEC)', category: 'HR & CSR', opportunityType: 'HR & CSR', priority: 'MEDIUM', platforms: 'Instagram + LinkedIn', status: 'Not Started', creativeBriefDue: '02 Oct 2026', round1Due: '17 Oct 2026', round2Due: '22 Oct 2026', finalCreativeDue: '27 Oct 2026', postConcept: null, visualDirection: null, captionDirection: null, creativeDue: null, notes: null },
]

async function main() {
  const hashedPassword = await bcrypt.hash('admin123', 10)

  // Admin user
  await prisma.user.upsert({
    where: { email: 'sims@admin.app' },
    update: {},
    create: {
      name: 'Karim',
      email: 'sims@admin.app',
      password: hashedPassword,
      role: 'ADMIN',
    },
  })

  // Approver 1
  await prisma.user.upsert({
    where: { email: 'editor@sims.app' },
    update: {},
    create: {
      name: 'Anda',
      email: 'editor@sims.app',
      password: await bcrypt.hash('admin123', 10),
      role: 'APPROVER',
    },
  })

  // Approver 2
  await prisma.user.upsert({
    where: { email: 'admin@sims.app' },
    update: {},
    create: {
      name: 'Mrs Veds',
      email: 'admin@sims.app',
      password: await bcrypt.hash('admin123', 10),
      role: 'APPROVER',
    },
  })

  // Clear existing data and re-seed (order matters for foreign keys)
  await prisma.mediaComment.deleteMany()
  await prisma.media.deleteMany()
  await prisma.comment.deleteMany()
  await prisma.approval.deleteMany()
  await prisma.reference.deleteMany()
  await prisma.notification.deleteMany()
  await prisma.event.deleteMany()
  for (const event of events) {
    await prisma.event.create({ data: event })
  }

  console.log('Seeded 92 events + 3 users')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
