const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

const events = [
  {
    number: 1, month: 'Jan', date: '01 Jan 2026', endDate: null,
    title: "New Year's Day", category: 'Social Greetings', opportunityType: 'Holiday Greeting',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds holiday greeting post in a styled look from AG',
    visualDirection: 'Festive, celebratory aesthetic',
    captionDirection: 'Warm, celebratory greeting',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '25 Dec 2025', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: 'need 6 territories national days',
  },
  {
    number: 2, month: 'Jan', date: '11 Jan 2026', endDate: null,
    title: 'Dubai Shopping Festival (DSF)', category: 'Brand Events', opportunityType: 'DSF Haul / Shop-With-Me',
    priority: 'CRITICAL', status: 'Not Started',
    postConcept: 'Mrs Veds shop-with-me across AG brand stores during DSF',
    visualDirection: 'Upbeat, in-mall BTS. Bags, tags, new finds. Energetic.',
    captionDirection: 'DSF haul — excitement-driven, discount callouts',
    platforms: 'Instagram Reel + TikTok + Story',
    creativeBriefDue: '21 Dec 2025', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: 'need to add gifting in Christmas Fitr Adha Diwali',
  },
  {
    number: 3, month: 'Jan', date: '07 Jan 2026', endDate: null,
    title: 'Lords of the Sound Orchestra', category: 'Brand Events', opportunityType: 'Content Opportunity',
    priority: 'LOW', status: 'Not Started',
    postConcept: 'Mrs Veds content tied to this moment',
    visualDirection: 'Brand-appropriate aesthetic',
    captionDirection: 'Authentic, on-brand caption',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '31 Dec 2025', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 4, month: 'Jan', date: '22 Jan 2026', endDate: null,
    title: 'Rob Beckett', category: 'Brand Events', opportunityType: 'Content Opportunity',
    priority: 'LOW', status: 'Not Started',
    postConcept: 'Mrs Veds content tied to this moment',
    visualDirection: 'Brand-appropriate aesthetic',
    captionDirection: 'Authentic, on-brand caption',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '15 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 5, month: 'Jan', date: '24 Jan 2026', endDate: null,
    title: 'International Day of Education', category: 'Social Greetings', opportunityType: 'Education & Empowerment Post',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds personal story on education, growth, and ambition',
    visualDirection: 'Warm, candid. Book/study aesthetic or aspirational portrait.',
    captionDirection: 'Education shaped who I am today — personal, inspiring',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '17 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 6, month: 'Jan', date: '24 Jan 2026', endDate: null,
    title: 'Hamlet by Jesús Herrera', category: 'Brand Events', opportunityType: 'Content Opportunity',
    priority: 'LOW', status: 'Not Started',
    postConcept: 'Mrs Veds content tied to this moment',
    visualDirection: 'Brand-appropriate aesthetic',
    captionDirection: 'Authentic, on-brand caption',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '17 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 7, month: 'Jan', date: '28 Jan 2026', endDate: null,
    title: 'Wicked The Musical', category: 'Brand Events', opportunityType: 'Content Opportunity',
    priority: 'LOW', status: 'Not Started',
    postConcept: 'Mrs Veds content tied to this moment',
    visualDirection: 'Brand-appropriate aesthetic',
    captionDirection: 'Authentic, on-brand caption',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '21 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 8, month: 'Jan', date: '31 Jan 2026', endDate: null,
    title: 'Sitar For Mental Health', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '24 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 9, month: 'Jan', date: '31 Jan 2026', endDate: null,
    title: 'Harvest Festival Hag Al Laila', category: 'Social Greetings', opportunityType: 'Heritage Cultural Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds celebrates Hag Al Laila — cultural styling, traditional treats',
    visualDirection: 'Traditional UAE aesthetic. Warm, nostalgic, cultural.',
    captionDirection: 'Hag Al Laila — celebrating our heritage — cultural pride',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '24 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 10, month: 'Jan', date: '31 Jan 2026', endDate: null,
    title: 'Dubai Fashion Week (SS26)', category: 'Brand Events', opportunityType: 'DFW Coverage / GRWM',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds attends/covers Dubai Fashion Week — GRWM, front row moments, trend reports',
    visualDirection: 'Fashion-forward, editorial. Street style aesthetic. Venue BTS.',
    captionDirection: 'DFW 2026 — the looks, the moments, the brands — fashion authority tone',
    platforms: 'Instagram Reel + Stories + TikTok',
    creativeBriefDue: '17 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 11, month: 'Feb', date: '04 Feb 2026', endDate: null,
    title: 'World Cancer Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '28 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 12, month: 'Feb', date: '07 Feb 2026', endDate: null,
    title: 'Rewind Fest DXB 2026', category: 'Brand Events', opportunityType: 'Content Opportunity',
    priority: 'LOW', status: 'Not Started',
    postConcept: 'Mrs Veds content tied to this moment',
    visualDirection: 'Brand-appropriate aesthetic',
    captionDirection: 'Authentic, on-brand caption',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '31 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 13, month: 'Feb', date: '08 Feb 2026', endDate: null,
    title: 'Lunar New Year Celebration', category: 'Social Greetings', opportunityType: 'Lunar New Year Lifestyle Post',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds Lunar New Year lifestyle content — celebration, culture, fashion',
    visualDirection: 'Rich reds and golds. Festive, cultural aesthetic.',
    captionDirection: 'Lunar New Year vibes — cultural, stylish, inclusive',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '01 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 14, month: 'Feb', date: '11 Feb 2026', endDate: null,
    title: 'Women & Girls in Science', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '04 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 15, month: 'Feb', date: '12 Feb 2026', endDate: null,
    title: 'Train Live', category: 'Brand Events', opportunityType: 'Content Opportunity',
    priority: 'LOW', status: 'Not Started',
    postConcept: 'Mrs Veds content tied to this moment',
    visualDirection: 'Brand-appropriate aesthetic',
    captionDirection: 'Authentic, on-brand caption',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '05 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 16, month: 'Feb', date: '13 Feb 2026', endDate: null,
    title: 'Chinese New Year', category: 'Social Greetings', opportunityType: 'CNY Styling / Cultural Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds Chinese New Year styling — red, gold, Year of the Horse',
    visualDirection: 'Red and gold. Celebratory, editorial feel. Lucky charms aesthetic.',
    captionDirection: 'Year of the Horse — new year, new looks — festive, inclusive',
    platforms: 'Instagram Feed + Reel + Story',
    creativeBriefDue: '06 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 17, month: 'Feb', date: '14 Feb 2026', endDate: null,
    title: "Valentine's Day", category: 'Social Greetings', opportunityType: 'Gifting Guide / OOTD',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds shares her top Valentine\'s picks from across AG brands',
    visualDirection: 'Warm tones, roses/pinks. Close-up of styled outfit + gift flatlay.',
    captionDirection: 'This Valentine\'s I\'m choosing [brand] for... — personal story-driven',
    platforms: 'Instagram Reel + Feed + Story',
    creativeBriefDue: '31 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 18, month: 'Feb', date: '15 Feb 2026', endDate: null,
    title: 'Tchaikovsky & Rachmaninoff', category: 'Brand Events', opportunityType: 'Content Opportunity',
    priority: 'LOW', status: 'Not Started',
    postConcept: 'Mrs Veds content tied to this moment',
    visualDirection: 'Brand-appropriate aesthetic',
    captionDirection: 'Authentic, on-brand caption',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '08 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 19, month: 'Feb', date: '16 Feb 2026', endDate: null,
    title: 'Hai Ramadan Starts', category: 'Social Greetings', opportunityType: 'Cultural Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds cultural heritage post with AG brand tie-in',
    visualDirection: 'Authentic, culturally grounded aesthetic',
    captionDirection: 'Pride and celebration of the cultural moment',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '09 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 20, month: 'Feb', date: '18 Feb 2026', endDate: null,
    title: 'Ramadan Begins', category: 'Brand Events', opportunityType: 'Ramadan Series (Multi-Week)',
    priority: 'CRITICAL', status: 'Not Started',
    postConcept: 'Mrs Veds Ramadan series — Iftar looks, suhoor moments, gifting guides',
    visualDirection: 'Warm amber, gold tones. Night market aesthetic. Lifestyle + fashion.',
    captionDirection: 'Ramadan Kareem — the looks, the mood, the gifting — series across 4 weeks',
    platforms: 'Instagram Reel Series + Story + TikTok',
    creativeBriefDue: '28 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 21, month: 'Feb', date: '20 Feb 2026', endDate: null,
    title: 'World Day of Social Justice', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '13 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 22, month: 'Feb', date: '22 Feb 2026', endDate: null,
    title: 'Desert Palm X-Country Run', category: 'Brand Events', opportunityType: 'Content Opportunity',
    priority: 'LOW', status: 'Not Started',
    postConcept: 'Mrs Veds content tied to this moment',
    visualDirection: 'Brand-appropriate aesthetic',
    captionDirection: 'Authentic, on-brand caption',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '15 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 23, month: 'Mar', date: '08 Mar 2026', endDate: null,
    title: "International Women's Day", category: 'Internal Communications', opportunityType: 'Women Empowerment Feature',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds shares her empowerment story + spotlights women at AG',
    visualDirection: 'Bold, empowering. Strong portrait. Candid behind-the-scenes.',
    captionDirection: 'To the women who showed me what strength looks like — personal, inspiring',
    platforms: 'Instagram Feed + Reel + LinkedIn',
    creativeBriefDue: '22 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 24, month: 'Mar', date: '18 Mar 2026', endDate: null,
    title: 'Global Recycling Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '11 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 25, month: 'Mar', date: '20 Mar 2026', endDate: null,
    title: 'Eid Al Fitr', category: 'Brand Events', opportunityType: 'Eid OOTD Collection Drop',
    priority: 'CRITICAL', status: 'Not Started',
    postConcept: 'Mrs Veds Eid collection — multiple Eid looks across AG brands, family/celebration',
    visualDirection: 'Festive, joyful, bright. Gold and jewel tones. Family/group setting.',
    captionDirection: 'Eid Mubarak — here\'s how I\'m celebrating in [brand] — joyful, fashion-forward',
    platforms: 'Instagram Reel + Feed + Story',
    creativeBriefDue: '27 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 26, month: 'Mar', date: '21 Mar 2026', endDate: null,
    title: "Mother's Day (UAE)", category: 'Social Greetings', opportunityType: 'Tribute / Gift Guide',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds shares a personal tribute to motherhood + curated gifting edit',
    visualDirection: 'Soft, emotional. Lifestyle imagery. Video message format ideal.',
    captionDirection: 'Heartfelt caption — personal story. Tag the mum in your life',
    platforms: 'Instagram Reel + Story',
    creativeBriefDue: '07 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 27, month: 'Mar', date: '22 Mar 2026', endDate: null,
    title: 'World Water Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '15 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 28, month: 'Apr', date: '07 Apr 2026', endDate: null,
    title: 'World Health Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '31 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 29, month: 'Apr', date: '15 Apr 2026', endDate: null,
    title: 'Great Online Sale', category: 'Brand Events', opportunityType: 'Online Haul Reveal',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds online shopping haul from AG e-commerce — unboxing',
    visualDirection: 'Flat lay unboxing. Home setting. Clean and aspirational.',
    captionDirection: 'Ordered during the Great Online Sale and I\'m OBSESSED — unboxing energy',
    platforms: 'Instagram Reel + TikTok',
    creativeBriefDue: '01 Apr 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 30, month: 'Apr', date: '01 Apr 2026', endDate: null,
    title: 'Token 2049', category: 'Brand Events', opportunityType: 'Web3 / Event Styling Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds attends Token 2049 — event OOTD, networking aesthetic from AG',
    visualDirection: 'Sleek, modern, tech-forward aesthetic. Event energy.',
    captionDirection: 'Token 2049 era — styled for the future — bold, forward-thinking',
    platforms: 'Instagram Reel + Story',
    creativeBriefDue: '25 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 31, month: 'Apr', date: '01 Apr 2026', endDate: null,
    title: 'Forever Living Rally', category: 'Brand Events', opportunityType: 'Content Opportunity',
    priority: 'LOW', status: 'Not Started',
    postConcept: 'Mrs Veds content tied to this moment',
    visualDirection: 'Brand-appropriate aesthetic',
    captionDirection: 'Authentic, on-brand caption',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '25 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 32, month: 'Apr', date: '01 Apr 2026', endDate: null,
    title: 'UITP Public Transport Summit', category: 'Brand Events', opportunityType: 'Content Opportunity',
    priority: 'LOW', status: 'Not Started',
    postConcept: 'Mrs Veds content tied to this moment',
    visualDirection: 'Brand-appropriate aesthetic',
    captionDirection: 'Authentic, on-brand caption',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '25 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 33, month: 'Apr', date: '21 Apr 2026', endDate: null,
    title: 'Creativity & Innovation Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '14 Apr 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 34, month: 'Apr', date: '22 Apr 2026', endDate: null,
    title: 'Earth Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '15 Apr 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 35, month: 'May', date: '01 May 2026', endDate: null,
    title: 'Labour Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '24 Apr 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 36, month: 'May', date: '08 May 2026', endDate: null,
    title: 'Dubai Esports & Games Festival', category: 'Social Greetings', opportunityType: 'Gaming / Esports Fashion Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds at the Esports Festival — casual/streetwear styling',
    visualDirection: 'Bold, youthful, colourful. Gaming aesthetic. Fun and energetic.',
    captionDirection: 'Levelling up my style at Esports — wearing [brand]',
    platforms: 'Instagram Reel + TikTok + Story',
    creativeBriefDue: '01 May 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 37, month: 'May', date: '22 May 2026', endDate: null,
    title: '3-Day Super Sale (1st Ed.)', category: 'Brand Events', opportunityType: 'Sale Picks / GRWM',
    priority: 'CRITICAL', status: 'Not Started',
    postConcept: 'Mrs Veds shares her top sale picks + GRWM for the sale',
    visualDirection: 'Bright, urgent energy. Countdown/GRWM format. Product close-ups.',
    captionDirection: 'The sale is LIVE — urgency + excitement',
    platforms: 'Instagram Reel + TikTok + Story',
    creativeBriefDue: '01 May 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 38, month: 'May', date: '26 May 2026', endDate: null,
    title: 'Arafat Day & Eid Al Adha', category: 'Brand Events', opportunityType: 'Eid Al Adha Styling',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds Eid Al Adha looks + gifting edit from AG brands',
    visualDirection: 'Rich, warm, traditional-inspired tones. Celebratory styling.',
    captionDirection: 'Eid Al Adha Mubarak — my Eid edit is here — warm, festive',
    platforms: 'Instagram Reel + Feed + Story',
    creativeBriefDue: '12 May 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 39, month: 'Jun', date: '05 Jun 2026', endDate: null,
    title: 'World Environment Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '29 May 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 40, month: 'Jun', date: '08 Jun 2026', endDate: null,
    title: "World Ocean's Day", category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '01 Jun 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 41, month: 'Jun', date: '16 Jun 2026', endDate: null,
    title: 'Islamic New Year (Hijri)', category: 'Social Greetings', opportunityType: 'Holiday Greeting',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds holiday greeting post in a styled look from AG',
    visualDirection: 'Festive, celebratory aesthetic',
    captionDirection: 'Warm, celebratory greeting',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '09 Jun 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 42, month: 'Jun', date: '21 Jun 2026', endDate: null,
    title: 'International Day of Yoga', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '14 Jun 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 43, month: 'Jun', date: '30 Jun 2026', endDate: null,
    title: 'World Social Media Day', category: 'Social Greetings', opportunityType: 'Behind-the-Scenes Creator Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds shares a BTS moment of her content creation process',
    visualDirection: 'Candid, authentic. Creator desk/studio aesthetic. Light, fun.',
    captionDirection: 'To every creator out there — thank you for inspiring me',
    platforms: 'Instagram Reel + Story',
    creativeBriefDue: '23 Jun 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 44, month: 'Jul', date: '03 Jul 2026', endDate: null,
    title: 'Dubai Summer Surprises (DSS)', category: 'Brand Events', opportunityType: 'Summer Edit / DSS Style Guide',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds seasonal summer edit — fashion, beauty, lifestyle picks from AG',
    visualDirection: 'Bright, summery, vibrant. Poolside or city lifestyle. Editorial.',
    captionDirection: 'Summer in Dubai means one thing... the DSS haul',
    platforms: 'Instagram Reel + Feed Series + Story',
    creativeBriefDue: '19 Jun 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 45, month: 'Jul', date: '15 Jul 2026', endDate: null,
    title: 'World Youth Skills Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '08 Jul 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 46, month: 'Jul', date: '30 Jul 2026', endDate: null,
    title: 'International Friendship Day', category: 'Social Greetings', opportunityType: 'Friends & Fashion Collab',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds + friend(s) styling moment — group OOTD from AG',
    visualDirection: 'Joyful, fun, group aesthetic. Bright and colourful.',
    captionDirection: 'The best accessory? Your best friend — styled by [brand]',
    platforms: 'Instagram Reel + Feed + Story',
    creativeBriefDue: '23 Jul 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 47, month: 'Aug', date: '12 Aug 2026', endDate: null,
    title: 'International Youth Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '05 Aug 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 48, month: 'Aug', date: '19 Aug 2026', endDate: null,
    title: 'World Humanitarian Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '12 Aug 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 49, month: 'Aug', date: '21 Aug 2026', endDate: null,
    title: 'World Entrepreneurs Day', category: 'Social Greetings', opportunityType: 'Entrepreneur Story',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds shares her entrepreneurship/creator journey',
    visualDirection: 'Confident, aspirational. Power pose or workspace aesthetic.',
    captionDirection: 'Building something you\'re proud of is the ultimate flex',
    platforms: 'Instagram Feed + Reel',
    creativeBriefDue: '14 Aug 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 50, month: 'Aug', date: '24 Aug 2026', endDate: null,
    title: "Prophet's Birthday", category: 'Social Greetings', opportunityType: 'Holiday Greeting',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds holiday greeting post in a styled look from AG',
    visualDirection: 'Festive, celebratory aesthetic',
    captionDirection: 'Warm, celebratory greeting',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '17 Aug 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 51, month: 'Aug', date: '25 Aug 2026', endDate: null,
    title: 'Back to School', category: 'Brand Events', opportunityType: 'Back to School OOTD / Styling Guide',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds styles back-to-school looks from AG brands — relatable, aspirational',
    visualDirection: 'Clean, fresh, school/campus aesthetic. Multiple outfit options.',
    captionDirection: 'Back to school era — styled by [brand] — aspirational + relatable',
    platforms: 'Instagram Reel + Carousel + Story',
    creativeBriefDue: '11 Aug 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 52, month: 'Aug', date: '28 Aug 2026', endDate: null,
    title: "Emirati Women's Day", category: 'Internal Communications', opportunityType: 'Emirati Heritage Styling',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds celebrates Emirati Women\'s Day — styled in traditional-inspired looks',
    visualDirection: 'Rich, proud aesthetics. Traditional colour palette. Portrait/editorial.',
    captionDirection: 'Proud to celebrate the strength of Emirati women — pride + identity',
    platforms: 'Instagram Feed + Story + Reel',
    creativeBriefDue: '14 Aug 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 53, month: 'Sep', date: '05 Sep 2026', endDate: null,
    title: 'International Day of Charity', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '29 Aug 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 54, month: 'Sep', date: '16 Sep 2026', endDate: null,
    title: 'Intl. Day of Ozone Layer', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '09 Sep 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 55, month: 'Sep', date: '23 Sep 2026', endDate: null,
    title: 'Saudi National Day', category: 'Social Greetings', opportunityType: 'Saudi National Day Feature',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds Saudi National Day content — Saudi pride, AG regional',
    visualDirection: 'Green and white tones. Saudi cultural references.',
    captionDirection: 'Happy Saudi National Day — celebrating with [brand] — regional pride',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '16 Sep 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 56, month: 'Oct', date: '01 Oct 2026', endDate: null,
    title: 'Pinktober (Breast Cancer)', category: 'Internal Communications', opportunityType: 'Pinktober Month-Long Series',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds wears pink across AG brands all October — awareness, support',
    visualDirection: 'Pink across all content. Soft, supportive aesthetic.',
    captionDirection: 'Pink October — wearing it with purpose — awareness, community',
    platforms: 'Instagram Weekly Posts + Story',
    creativeBriefDue: '17 Sep 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 57, month: 'Oct', date: '10 Oct 2026', endDate: null,
    title: 'World Mental Health Day', category: 'Social Greetings', opportunityType: 'Mental Health Check-In',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds shares a candid, authentic mental health moment',
    visualDirection: 'Soft, quiet aesthetic. Natural light. No heavy branding.',
    captionDirection: 'Checking in on yourself is the most important thing — gentle, human',
    platforms: 'Instagram Story Series + Feed Post',
    creativeBriefDue: '26 Sep 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 58, month: 'Oct', date: '16 Oct 2026', endDate: null,
    title: 'Dubai Home Festival', category: 'Social Greetings', opportunityType: 'Home Styling / Lifestyle Edit',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds home lifestyle edit — interiors-inspired fashion + home picks',
    visualDirection: 'Cosy, aesthetic interior shots. Lifestyle fashion context.',
    captionDirection: 'Home is where the style is — my picks from [brand]',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '09 Oct 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 59, month: 'Oct', date: '31 Oct 2026', endDate: null,
    title: 'Halloween', category: 'Social Greetings', opportunityType: 'Costume / Fashion Moment',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds in a creative Halloween look styled from AG brands — fun, on-trend',
    visualDirection: 'Dark/moody aesthetic. Dramatic look. BTS + final reveal format.',
    captionDirection: 'Playful, fun tone. Reveal format. Dressed by [brand]',
    platforms: 'Instagram Reel + TikTok + Story',
    creativeBriefDue: '17 Oct 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 60, month: 'Oct', date: '31 Oct 2026', endDate: null,
    title: 'Dubai Fitness Challenge (30x30)', category: 'Social Greetings', opportunityType: 'DFC Fitness Style Series',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds 30x30 challenge journey — activewear styling from AG brands',
    visualDirection: 'Active, energetic, outdoor. Workout aesthetic, bright and healthy.',
    captionDirection: '30 days, 30 mins — joining the DFC in [brand activewear] — challenge energy',
    platforms: 'Instagram Reel Series + Story + TikTok',
    creativeBriefDue: '17 Oct 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 61, month: 'Nov', date: '02 Nov 2026', endDate: null,
    title: 'Diwali', category: 'Social Greetings', opportunityType: 'Diwali Fashion & Gifting',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds Diwali styling — festive, colourful looks + gifting from AG',
    visualDirection: 'Jewel tones, candles, festive diyas. Rich and celebratory.',
    captionDirection: 'Diwali with [brand] — the looks that light up the room — warm, inclusive',
    platforms: 'Instagram Feed + Reel + Story',
    creativeBriefDue: '19 Oct 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 62, month: 'Nov', date: '03 Nov 2026', endDate: null,
    title: 'UAE Flag Day', category: 'Social Greetings', opportunityType: 'Awareness Moment',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds marks the awareness day with a personal authentic post',
    visualDirection: 'Clean, purposeful aesthetic',
    captionDirection: 'Personal, empathetic caption tied to the awareness theme',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '27 Oct 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 63, month: 'Nov', date: '27 Nov 2026', endDate: null,
    title: 'Black Friday (White Friday)', category: 'Brand Events', opportunityType: 'White Friday Wishlist Drop',
    priority: 'CRITICAL', status: 'Not Started',
    postConcept: 'Mrs Veds reveals her White Friday wishlist live — countdown to deals',
    visualDirection: 'Bold sale aesthetics. Black/white tones. Countdown + haul format.',
    captionDirection: 'My White Friday wishlist — Use my code [X] for extra — affiliate energy',
    platforms: 'Instagram Reel + TikTok + Story',
    creativeBriefDue: '06 Nov 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 64, month: 'Nov', date: '30 Nov 2026', endDate: null,
    title: 'Commemoration Day', category: 'Social Greetings', opportunityType: 'Holiday Greeting',
    priority: 'MEDIUM', status: 'Not Started',
    postConcept: 'Mrs Veds holiday greeting post in a styled look from AG',
    visualDirection: 'Festive, celebratory aesthetic',
    captionDirection: 'Warm, celebratory greeting',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '23 Nov 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 65, month: 'Dec', date: '02 Dec 2026', endDate: null,
    title: 'UAE National Day', category: 'Social Greetings', opportunityType: 'UAE Pride / National Day OOTD',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds National Day look — UAE flag colours, patriotic styling',
    visualDirection: 'Red, white, green, black. UAE flag backdrop. Pride and celebration.',
    captionDirection: 'Happy National Day — 55 years of dreams — proud, celebratory',
    platforms: 'Instagram Feed + Story + Reel',
    creativeBriefDue: '18 Nov 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 66, month: 'Dec', date: '25 Dec 2026', endDate: null,
    title: 'Christmas Day', category: 'Social Greetings', opportunityType: 'Gifting Haul / Christmas OOTD',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds Christmas gifting haul + festive OOTD across AG brands',
    visualDirection: 'Festive, warm, cosy. Home setting with gifting. Unboxing style.',
    captionDirection: 'My Christmas picks from [brand] — authentic, warm tone',
    platforms: 'Instagram Reel + Feed + Story',
    creativeBriefDue: '11 Dec 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 67, month: 'Dec', date: '31 Dec 2026', endDate: null,
    title: "New Year's Eve", category: 'Social Greetings', opportunityType: 'Brand Campaign Feature',
    priority: 'HIGH', status: 'Not Started',
    postConcept: 'Mrs Veds styled look tied to the campaign theme',
    visualDirection: 'On-brand aesthetic matching campaign',
    captionDirection: 'Campaign-aligned caption with brand mention',
    platforms: 'Instagram Feed + Story',
    creativeBriefDue: '17 Dec 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 68, month: 'Jan', date: '19 Jan 2026', endDate: '23 Jan 2026',
    title: 'World Economic Forum (Davos)', category: 'Conferences', opportunityType: 'Thought Leadership',
    priority: 'CRITICAL', status: 'Planned',
    postConcept: 'LinkedIn article: Mrs Veds on retail resilience and the future of MENA commerce',
    visualDirection: 'Professional backdrop or branded graphic. WEF/Forbes visual context.',
    captionDirection: 'At Davos, one theme stands clear: the future of retail belongs to purpose-driven leaders',
    platforms: 'LinkedIn + Twitter/X',
    creativeBriefDue: '02 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 69, month: 'Feb', date: '03 Feb 2026', endDate: '04 Feb 2026',
    title: 'RLC Global Forum (Riyadh)', category: 'Conferences', opportunityType: 'Thought Leadership / Speaking',
    priority: 'CRITICAL', status: 'Planned',
    postConcept: 'Speaking moment or post-event recap reel at the RLC Global Forum',
    visualDirection: 'Stage photography branded event backdrop candid leadership shots.',
    captionDirection: 'Honoured to join top retail leaders at RLC discussing the future of commerce',
    platforms: 'LinkedIn + Instagram Reel + Story',
    creativeBriefDue: '14 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 70, month: 'Feb', date: '11 Feb 2026', endDate: null,
    title: 'New York Fashion Week', category: 'Social Greetings', opportunityType: 'Trend Commentary',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Reel or Carousel: Mrs Veds NYFW trend picks — what to watch for AW26/27',
    visualDirection: 'Mood board aesthetic: fashion week energy, editorial palette.',
    captionDirection: 'NYFW kicks off fashion month — here are the trends I am tracking for the region',
    platforms: 'Instagram Reel + Feed + Story',
    creativeBriefDue: '21 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 71, month: 'Feb', date: '11 Feb 2026', endDate: null,
    title: 'Retail Reboot Summit', category: 'Conferences', opportunityType: 'Speaking / Panel',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Recap post from Address Sky View summit — retail innovation',
    visualDirection: 'Event photography panel moments branded summit backdrop.',
    captionDirection: 'The future of retail is being written now — proud to contribute',
    platforms: 'LinkedIn + Instagram Story',
    creativeBriefDue: '21 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 72, month: 'Feb', date: '19 Feb 2026', endDate: null,
    title: 'London Fashion Week', category: 'Social Greetings', opportunityType: 'Trend Commentary / OOTD',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Style reaction post or LFW trend review',
    visualDirection: 'Editorial tones: grey/black/white fashion week aesthetic.',
    captionDirection: 'London Fashion Week never disappoints. My top picks from LFW AW26/27',
    platforms: 'Instagram Feed + Reel + Story',
    creativeBriefDue: '29 Jan 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 73, month: 'Mar', date: '02 Mar 2026', endDate: '10 Mar 2026',
    title: 'Milan Fashion Week', category: 'Social Greetings', opportunityType: 'Trend Commentary / OOTD',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Milan MFW highlights reel — luxury heritage brands, craftsmanship',
    visualDirection: 'Rich, warm tones. Duomo backdrop or luxury editorial styling.',
    captionDirection: 'Milan speaks in quality and heritage. My MFW edit for this season',
    platforms: 'Instagram Reel + Feed + LinkedIn',
    creativeBriefDue: '17 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 74, month: 'Mar', date: '06 Mar 2026', endDate: '08 Mar 2026',
    title: 'F1 Australian Grand Prix', category: 'Brand Events', opportunityType: 'Lifestyle / Brand Activation',
    priority: 'MEDIUM', status: 'Planned',
    postConcept: 'F1 season opener lifestyle content — Mrs Veds OOTD at a watch party',
    visualDirection: 'Racing glamour aesthetic. Bold colours, speed-inspired styling.',
    captionDirection: 'The F1 season is ON. And the fashion game at the paddock? Always on point.',
    platforms: 'Instagram Feed + Story + Reel',
    creativeBriefDue: '15 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 75, month: 'Mar', date: '09 Mar 2026', endDate: '19 Mar 2026',
    title: 'UN CSW70', category: 'Internal Communications', opportunityType: 'Women Empowerment / Advocacy',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'LinkedIn article aligned with IWD momentum — women in leadership',
    visualDirection: 'Empowerment graphic or branded quote card. UN CSW theme colours.',
    captionDirection: 'At CSW70 the world is asking: are we truly giving to gain?',
    platforms: 'LinkedIn + Instagram Story',
    creativeBriefDue: '26 Feb 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 76, month: 'Mar', date: '28 Mar 2026', endDate: null,
    title: 'Dubai World Cup (30th Anniversary)', category: 'Social Greetings', opportunityType: 'Lifestyle / Fashion Moment',
    priority: 'CRITICAL', status: 'Planned',
    postConcept: 'Mrs Veds OOTD + Dubai World Cup 30th anniversary — elite fashion at Meydan',
    visualDirection: 'Glamorous raceday styling. Bold hats, florals, luxury looks.',
    captionDirection: 'The Dubai World Cup — where fashion meets horsepower. 30 legendary years.',
    platforms: 'Instagram Feed + Reel + Story',
    creativeBriefDue: '07 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 77, month: 'Apr', date: '08 Apr 2026', endDate: '10 Apr 2026',
    title: 'Paris Fashion Week', category: 'Social Greetings', opportunityType: 'Trend Commentary / OOTD',
    priority: 'CRITICAL', status: 'Planned',
    postConcept: 'PFW couture moment — Mrs Veds top picks, OOTD, brand commentary',
    visualDirection: 'Parisian aesthetic: Eiffel Tower, haute couture styling, editorial palette.',
    captionDirection: 'Paris Fashion Week — the pinnacle. Here is everything I loved from PFW.',
    platforms: 'Instagram Reel + Feed + Story + LinkedIn',
    creativeBriefDue: '20 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 78, month: 'Apr', date: '10 Apr 2026', endDate: '12 Apr 2026',
    title: 'F1 Bahrain Grand Prix', category: 'Brand Events', opportunityType: 'Lifestyle / Brand Activation',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Bahrain F1 — hospitality suite or paddock fashion content',
    visualDirection: 'Racing day glamour. Bahrain circuit aesthetic, branded corporate hospitality.',
    captionDirection: 'Bahrain Grand Prix. The Middle East F1 season begins',
    platforms: 'Instagram Feed + Story + Reel',
    creativeBriefDue: '22 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 79, month: 'Apr', date: '13 Apr 2026', endDate: '16 Apr 2026',
    title: 'LEAP Tech Conference', category: 'Conferences', opportunityType: 'Thought Leadership',
    priority: 'CRITICAL', status: 'Planned',
    postConcept: 'LEAP keynote or panel recap — retail technology, AI, future of commerce',
    visualDirection: 'Tech conference aesthetics. Riyadh skyline, stage photography.',
    captionDirection: 'At LEAP2026: AI is reshaping retail faster than ever',
    platforms: 'LinkedIn + Twitter/X + Instagram Story',
    creativeBriefDue: '26 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 80, month: 'Apr', date: '14 Apr 2026', endDate: '18 Apr 2026',
    title: 'Arab Women Week & Summit (London)', category: 'Internal Communications', opportunityType: 'Women Empowerment / Speaking',
    priority: 'CRITICAL', status: 'Planned',
    postConcept: 'Lancaster House speaking engagement — Arab women in global leadership',
    visualDirection: 'Prestigious venue photography. Lancaster House interior, polished styling.',
    captionDirection: 'At Arab Women Week Summit in London — honoured to share the stage',
    platforms: 'LinkedIn + Instagram Feed + Reel',
    creativeBriefDue: '28 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 81, month: 'Apr', date: '17 Apr 2026', endDate: '19 Apr 2026',
    title: 'F1 Saudi Arabian GP', category: 'Brand Events', opportunityType: 'Lifestyle / Brand Activation',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Jeddah F1 — corporate hospitality + luxury automotive synergy',
    visualDirection: 'Bold Saudi national spirit meets luxury fashion. Jeddah corniche backdrop.',
    captionDirection: 'Jeddah Formula One. Where speed meets style in the Kingdom.',
    platforms: 'Instagram Feed + Story + Reel',
    creativeBriefDue: '29 Mar 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 82, month: 'May', date: '04 May 2026', endDate: '07 May 2026',
    title: 'Arabian Travel Market (ATM)', category: 'Conferences', opportunityType: 'Brand Visibility / Retail Tie-in',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'ATM walkthrough content — Mrs Veds on travel retail and AG global footprint',
    visualDirection: 'ATM DWTC event backdrop. Polished, travel-inspired styling.',
    captionDirection: 'At ATMDubai — the intersection of global travel and luxury retail.',
    platforms: 'LinkedIn + Instagram Story',
    creativeBriefDue: '16 Apr 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 83, month: 'May', date: '26 May 2026', endDate: null,
    title: 'Day of Arafah', category: 'Social Greetings', opportunityType: 'Cultural / Spiritual Reflection',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Heartfelt reflective post — spiritual or gratitude message ahead of Eid Al Adha',
    visualDirection: 'Serene, warm tones. Soft lighting, minimal aesthetic.',
    captionDirection: 'On this sacred Day of Arafah, a moment of reflection and gratitude',
    platforms: 'Instagram Story + Feed',
    creativeBriefDue: '05 May 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 84, month: 'Sep', date: '01 Sep 2026', endDate: '06 Sep 2026',
    title: 'Dubai Fashion Week (SS27)', category: 'Social Greetings', opportunityType: 'Fashion / Brand Moment',
    priority: 'CRITICAL', status: 'Planned',
    postConcept: 'DFW SS27 — front row, backstage access, OOTD series, brand showcase',
    visualDirection: 'Dubai d3 aesthetic. Front-row fashion photography, designer encounters.',
    captionDirection: "Dubai Fashion Week SS27 — the region's most electric fashion moment",
    platforms: 'Instagram Reel + Feed + Story + LinkedIn',
    creativeBriefDue: '16 Aug 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 85, month: 'Oct', date: '05 Oct 2026', endDate: '06 Oct 2026',
    title: 'Retail Congress MENA', category: 'Conferences', opportunityType: 'Thought Leadership / Speaking',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Retail Congress panel or keynote recap — future of MENA retail strategy',
    visualDirection: 'Conference photography. Dubai skyline backdrop, professional styling.',
    captionDirection: 'At Retail Congress MENA — conversations shaping the future of retail',
    platforms: 'LinkedIn + Instagram Story',
    creativeBriefDue: '15 Sep 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 86, month: 'Oct', date: '06 Oct 2026', endDate: '08 Oct 2026',
    title: 'ME Women Leaders Summit & Awards (KSA)', category: 'Internal Communications', opportunityType: 'Women Empowerment / Award',
    priority: 'CRITICAL', status: 'Planned',
    postConcept: 'Summit attendance + award recognition. Mrs Veds speech moment',
    visualDirection: 'Award gala photography. Elegant KSA venue, red carpet or stage moment.',
    captionDirection: 'The 6% barrier in executive leadership must be broken.',
    platforms: 'LinkedIn + Instagram Feed + Reel',
    creativeBriefDue: '17 Sep 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 87, month: 'Oct', date: '26 Oct 2026', endDate: '28 Oct 2026',
    title: 'Gifts & Lifestyle Middle East', category: 'Conferences', opportunityType: 'B2B / Brand Partnership',
    priority: 'MEDIUM', status: 'Planned',
    postConcept: 'Trade show walkthrough — discovering premium gifting partners',
    visualDirection: 'Trade show aesthetic. DWTC venue, product flat lays, brand discovery.',
    captionDirection: 'At Gifts & Lifestyle ME — discovering beautiful gifting concepts',
    platforms: 'Instagram Story + LinkedIn',
    creativeBriefDue: '07 Oct 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 88, month: 'Nov', date: '04 Nov 2026', endDate: null,
    title: 'EcoNext ESG Conference', category: 'Conferences', opportunityType: 'ESG / Sustainability',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Mrs Veds on AG sustainability journey — ESG commitments',
    visualDirection: 'Clean, green aesthetic. Sustainability-themed visual language.',
    captionDirection: 'Sustainability is no longer optional — it is the only path forward.',
    platforms: 'LinkedIn + Instagram Story + Feed',
    creativeBriefDue: '14 Oct 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 89, month: 'Nov', date: '11 Nov 2026', endDate: null,
    title: "Singles Day (11.11)", category: 'Brand Events', opportunityType: 'E-Commerce / Campaign',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Mrs Veds curated 11.11 picks across AG brands — style guide and deals',
    visualDirection: 'Bold graphic with 11.11 branding. Energetic, deal-focused aesthetic.',
    captionDirection: '11.11 is HERE and I have handpicked my favourites across our brands.',
    platforms: 'Instagram Feed + Story + Reel + TikTok',
    creativeBriefDue: '21 Oct 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 90, month: 'Nov', date: '27 Nov 2026', endDate: '29 Nov 2026',
    title: 'F1 Qatar Grand Prix', category: 'Brand Events', opportunityType: 'Lifestyle / Brand Activation',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Qatar F1 — championship finale energy. Fashion content at Lusail.',
    visualDirection: 'Night race glamour. Lusail Circuit lights, bold luxury styling.',
    captionDirection: 'Lusail at night — the F1 finale energy is unmatched. QatarGP.',
    platforms: 'Instagram Feed + Reel + Story',
    creativeBriefDue: '08 Nov 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 91, month: 'Nov', date: '30 Nov 2026', endDate: null,
    title: 'Cyber Monday', category: 'Brand Events', opportunityType: 'E-Commerce / Campaign',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'Last-chance campaign post — Cyber Monday picks across AG brands',
    visualDirection: 'Bold, digital aesthetic. Screen-focused or tech-forward styling.',
    captionDirection: 'Cyber Monday is your LAST chance for incredible deals.',
    platforms: 'Instagram Feed + Story + Email',
    creativeBriefDue: '09 Nov 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 92, month: 'Dec', date: '04 Dec 2026', endDate: '06 Dec 2026',
    title: 'F1 Abu Dhabi Grand Prix', category: 'Brand Events', opportunityType: 'Lifestyle / Hospitality',
    priority: 'CRITICAL', status: 'Planned',
    postConcept: 'Season finale on Yas Island — OOTD + corporate hospitality',
    visualDirection: 'Yas Island luxury aesthetic. Sunset over the circuit, glamour hospitality.',
    captionDirection: 'The final lap of the F1 season — Abu Dhabi saves the BEST for last.',
    platforms: 'Instagram Reel + Feed + Story + LinkedIn',
    creativeBriefDue: '15 Nov 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 93, month: 'Dec', date: '07 Dec 2026', endDate: '11 Dec 2026',
    title: 'GITEX Global', category: 'Conferences', opportunityType: 'Tech / Thought Leadership',
    priority: 'HIGH', status: 'Planned',
    postConcept: 'GITEX walkthrough — retail tech, AI in fashion, AG digital future',
    visualDirection: 'Tech expo energy. Dubai Expo City venue, innovation-focused visual.',
    captionDirection: 'At GITEX2026 — the future of retail is AI-powered.',
    platforms: 'LinkedIn + Instagram Story + Twitter/X',
    creativeBriefDue: '20 Nov 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 94, month: 'Dec', date: '14 Dec 2026', endDate: '15 Dec 2026',
    title: "Forbes ME Women's Summit (Riyadh)", category: 'Internal Communications', opportunityType: "Women Empowerment / Speaking",
    priority: 'CRITICAL', status: 'Planned',
    postConcept: 'Forbes ME Women Summit 4th edition — speaker or honoree',
    visualDirection: 'Forbes summit stage photography. Elegant Riyadh venue, award-night styling.',
    captionDirection: 'Limitless Inspiration — that is the theme at Forbes ME Women 2026.',
    platforms: 'LinkedIn + Instagram Reel + Feed',
    creativeBriefDue: '24 Nov 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
  {
    number: 95, month: 'Dec', date: '18 Dec 2026', endDate: null,
    title: 'Qatar National Day', category: 'Social Greetings', opportunityType: 'Cultural / Brand Acknowledgement',
    priority: 'MEDIUM', status: 'Planned',
    postConcept: 'Qatar National Day greeting — acknowledging AG presence in Qatar',
    visualDirection: 'Qatar maroon and white palette. National pride visual.',
    captionDirection: 'Wishing our friends and partners in Qatar a proud National Day.',
    platforms: 'Instagram Story + LinkedIn',
    creativeBriefDue: '27 Nov 2026', round1Due: null, round2Due: null, finalCreativeDue: null, creativeDue: null,
    notes: null,
  },
]

async function main() {
  const hashedPassword = await bcrypt.hash('admin123', 10)

  // Admin user
  await prisma.user.upsert({
    where: { email: 'sims@admin.app' },
    update: {},
    create: {
      name: 'Karim',
      email: 'sims@admin.app',
      password: hashedPassword,
      role: 'ADMIN',
    },
  })

  // Approver 1
  await prisma.user.upsert({
    where: { email: 'editor@sims.app' },
    update: {},
    create: {
      name: 'Anda',
      email: 'editor@sims.app',
      password: await bcrypt.hash('admin123', 10),
      role: 'APPROVER',
    },
  })

  // Approver 2
  await prisma.user.upsert({
    where: { email: 'admin@sims.app' },
    update: {},
    create: {
      name: 'Mrs Veds',
      email: 'admin@sims.app',
      password: await bcrypt.hash('admin123', 10),
      role: 'APPROVER',
    },
  })

  // Clear existing data and re-seed (order matters for foreign keys)
  await prisma.mediaComment.deleteMany()
  await prisma.media.deleteMany()
  await prisma.comment.deleteMany()
  await prisma.approval.deleteMany()
  await prisma.reference.deleteMany()
  await prisma.notification.deleteMany()
  await prisma.event.deleteMany()
  for (const event of events) {
    await prisma.event.create({ data: event })
  }

  console.log('Seeded 95 events + 3 users')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
